# -*- coding: utf-8 -*-
"""
Configuration Package for Digital Twin Warehouse Simulator
Exports all settings and color constants
"""

from subsystems.config.settings import *
from subsystems.config.colors import *

__all__ = [
    # From settings
    'SUPPORTED_RESOLUTIONS',
    'LOGICAL_WIDTH',
    'LOGICAL_HEIGHT',
    'CAPACIDAD_TRASPALETA',
    'CAPACIDAD_MONTACARGAS',
    'PANEL_WIDTH',
    'DEFAULT_TILE_WIDTH',
    'DEFAULT_TILE_HEIGHT',
    'INTERVALO_ACTUALIZACION_METRICAS',
    'TIEMPO_DESCARGA_POR_TAREA',
    'NUM_OPERARIOS_TERRESTRES_DEFAULT',
    'NUM_MONTACARGAS_DEFAULT',
    'COSTO_MOVIMIENTO_NORMAL',
    'COSTO_MOVIMIENTO_DIAGONAL',
    'TOTAL_ORDENES_DEFAULT',
    'CAPACIDAD_CARRO_DEFAULT',
    'DEFAULT_LAYOUT_FILE',
    'DEFAULT_SEQUENCE_FILE',
    # From colors
    'COLOR_FONDO',
    'COLOR_FONDO_OSCURO',
    'COLOR_AGENTE_TERRESTRE',
    'COLOR_AGENTE_MONTACARGAS',
    'COLOR_AGENTE_IDLE',
    'COLOR_AGENTE_TRABAJANDO',
    'COLOR_AGENTE_MOVIENDO',
    'COLOR_TAREA_PENDIENTE',
    'COLOR_TAREA_ASIGNADA',
    'COLOR_TAREA_EN_PROGRESO',
    'COLOR_TAREA_COMPLETADA',
    'COLOR_AREA_CAMINABLE',
    'COLOR_OBSTACULO',
    'COLOR_PUNTO_PICKING',
    'COLOR_DEPOT',
    'COLOR_AREA_TRABAJO',
    'COLOR_DASHBOARD_BG',
    'COLOR_DASHBOARD_TEXTO',
    'COLOR_DASHBOARD_BORDE',
    'COLOR_DASHBOARD_HIGHLIGHT',
    'COLOR_EXITO',
    'COLOR_ADVERTENCIA',
    'COLOR_ERROR',
    'COLOR_INFO',
    'COLOR_TEXTO',
    'COLOR_TEXTO_SECUNDARIO',
    'COLOR_TEXTO_CLARO',
    'COLOR_GRID',
    'COLOR_CAMINO',
    'COLOR_CAMINO_BLOQUEADO',
    'COLOR_TRANSPARENTE',
    'COLOR_SELECCION',
    'COLOR_DEBUG',
]
